---
- name: Setup the jenkins server
  hosts: jenkinsserver
  tasks:
   - name: Install java,git,maven
     apt:
      name: "{{item}}"
      state: present
     with_items:
      - openjdk-8-jdk
      - git
      - maven
   - name: Download jenkins.war
     get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: /tmp
   - name: Start jenkins
     shell: java -jar /tmp/jenkins.war
- name: Setup tomcat on QA and prodservers
  hosts: servers
  tasks:
   - name: Install tomcat8 and tomcat8-admin
     apt:
      name: "{{item}}"
      state: present
     with_items:
      - tomcat8
      - tomcat8-admin
   - name: Copy tomcat-users.xml file
     copy:
      src: /home/ubuntu/tomcat-users.xml
      dest: /etc/tomcat8
   - name: Restart tomcat8
     service:
      name: tomcat8
      state: restarted




