---
- name: Implementing tags
  hosts: all
  tasks:
   - name: Install tree
     apt:
      name: tree
      state: present
     tags: tree_installation
   - name: Create a user
     user:
      name: Rabi
      password: intelliq
     tags: user_creation
   - name: copy the passwd file
     copy:
      src: /etc/passwd
      dest: /tmp

